version: "3.0"

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
  app:
    build: ./php
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql
    environment:
        MYSQL_DATABASE: test_php
        MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/etc/mysql/conf.d:/etc/mysql/conf.d